config/routes.rb
Rails.application.routes.draw do

get "dashboard_contractor", to: "pages#dashboard_contractor"
get "dashboard_client", to: "pages#dashboard_client"
get "about", to: "pages#about"
  devise_for :users
  root to: 'services#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :services do
    resources :bookings do
      resources :reviews, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :client
  has_one :contractor, through: :service
  has_many :reviews, dependent: :destroy

  validates :date, presence: true

  def self.link_contractor(contractor)
    joins(:service).where(services: { contractor: contractor })
  end

end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  belongs_to :user
  has_many :services
  has_many :bookings, through: :services
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :service
  mount_uploader :url, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :pictures, as: :picturable
  belongs_to :booking

  validates :rating, presence: true, inclusion: {in: (0..5)}
  validates :description, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :contractor
  has_many :pictures, inverse_of: :service
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  accepts_nested_attributes_for :pictures

  validates :name, presence: true
  validates :description, presence: true
  validates :name, presence: true
  validates :location, presence: true
  validates :category, presence: true
  mount_uploader :photo, PhotoUploader

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/user.rb
class User < ApplicationRecord

  has_one :contractor, dependent: :destroy
  has_one :client, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :avatar, PhotoUploader

  after_create_commit :create_profile,

  def create_profile
    Client.new(user: self).save
    Contractor.new(user: self).save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_new_service
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
  end
  def set_new_service
    @newservice = Service.new
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
    @service = @booking.service
    @review = Review.new
  end

  def new
    @booking = Booking.new
    @booking.service = Service.find(params[:service_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.client = current_user.client
    @booking.service = Service.find(params[:service_id])
    @booking.save
    redirect_to service_booking_path(@booking.service, @booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to :root
  end

  private

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard_contractor
    @services = Service.all
    @bookings_count = Booking.link_contractor(current_user.contractor).count
    @cashed_in = Booking.link_contractor(current_user.contractor).sum(:price)
    @bookings_list = Booking.link_contractor(current_user.contractor)
  end

  def dashboard_client
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review  = Review.new(review_params)
    @service = @booking.service
    @review.booking = @booking
    if @review.save
      respond_to do |format|
        flash[:notice]="Review saved"
        format.html { redirect_to service_path(@service)}
      end
    else
      respond_to do |format|
        flash[:error]="Something went wrong"
        format.html { redirect_to service_path(@service)}
    end
  end
end

  private

  def review_params
    params.require(:review).permit(:booking_id, :service_id, :rating, :description)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :set_service, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, except: [:create, :update, :destroy]

  def index

   respond_to do |format|
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query"
      @services = Service.where(sql_query, query: "%#{params[:query]}%")

      format.js
    else
      @services = Service.all
      format.html
    end
   end
  end

  def contractor_services
    @contractor_services = current_user.contractor.services
  end

  def show
     @booking = Booking.new
     @markers =[{ 'lat': @service.latitude, 'lng': @service.longitude }]
  end

  def edit

  end

  def update
    @service.update(service_params)
    redirect_to service_path(@service)
  end

  def destroy

    @service.destroy
    redirect_to services_path
  end

  def new
    @service = Service.new
    @user = current_user
  end

  def create

    @service = Service.new(service_params)
    @contractor = current_user.contractor
    @service.contractor = @contractor
    if @service.save!
      redirect_to service_path(@service)
    else
      render :new
    end
  end

  private
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :description, :price, :location, :category, :photo )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/tHF1OBF/4k-organized-criminal-gangsters-in-dark-parking-lot-doing-a-drug-deal_h7fugeodye_thumbnail-full01.png');">

  <div class="picture" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.massimovillas.com/wp-content/uploads/2016/04/villa-in-tuscany-italy-767x350.jpg');">
  </div>

<div class="tittle" >
  <h1>Your Booking summary</h1>


</div>
<div class="box">
  <p><%= @booking.date %></p>
  <p style="font-size: 35px"><%= @booking.service.name %></p>
  <p style="font-size: 25px; margin-top: 5px;"><%= @booking.service.category %></p>
  <p style= "margin-right: 60px;"><h4>Price: <%= @booking.service.price%></h4>
  </p>
  <p style= "margin-right: 40px;"><h4><%=@booking.service.location%></h4>
  </p>
<%= render 'reviews/form', service: @service, booking: @booking, review: @review %>

</div>
</div>


<div id="reviews">
  <% if @booking.service.reviews.blank? %>
    Be the first to leave a review for <%= @booking.service.name %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>ServiceFinder</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <!-- Include Date Range Picker -->
  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <div class="container-body">
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  </div>
  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>

  <%= javascript_pack_tag 'application' %>
   <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag 'map' %>

</body>
</html>

app/views/pages/about.html.erb
<div class="about-title">
<h1>About us</h1>

</div>
<div id="titles">
  <div id="titlecontent">
    <div class="avatars-about">
      <p>
        <div class="avatar-about">
          <%= image_tag("fotopp.jpg", size: "300x300", class: 'avatar-about') %>
        </div>
      </p>
      <p>
        <div class="avatar-about">
         <%= image_tag("https://files.slack.com/files-pri/T02NE0241-F9UA2HRS7/rb.jpg", size: "300x300", class: 'avatar-about') %>
       </div>
     </p>
     <p>
       <div class="avatar-about">
         <%= image_tag("https://ca.slack-edge.com/T02NE0241-U939Q8KR7-160c90d65b5d-512", size: "300x300", class: 'avatar-about') %>
       </div>
     </p>
   </div>

  <p>
    We are a team of programmers from LeWagon Brussels.
     This is a project for our class on the batch #133   2018.
     We like coding but we also love life! Hiking, Surfing..etc.
     Daniel came from Galicia as a young boy, groomed to be a barber apprentice. He had a difficult relation with his tutor, a severe man who had lost his wife at an early age and enjoyed drinking above the normal standard.
     After a serious of grievances and many customers with funny looking hairdos, Daniel searched for another path that ran closer to his heart: raising chicken.
     He's been highly proficuous at his job, reaching an impressive record of 1 million heads, whom he knew by first name.
     It wasn't until Jasmine, one of his chicken, couldn't find the right partner, that he thought about building a dating site for the litle animals. He found Le Wagon and has since progressed tremendously in his skills as a programmer. Jasmine won't be alone for much longer.

     Georges was a renowed surfer on the coast of Malibu. He descended directly from a Kanaka Maoli king, a ruler in acient Hawai, who traded directly with Francis Cook.
     The genetic love for the ocean and free outdoors perdured in Georges, whose dextery and sheer courage was unmatched among his friends. Beautiful girls orbited around this poseidon.
     It wasn't until one day when he fell hard from the sufboard and hit hard with his head that he felt suddenly unconfortable in the ocean, and even annoyed by being wet. He rushed home walking very fast under a blazing sun and was only stopped by a lady, who had some difficulties finding the directions to her son's house on her phone. Without any previous background, Georges fixed the bug in the geo location on Google's API, leading the lady safely to her destination.
     Ruben wrote this bullshit.
      Hope you enjoy our first work together!
  </p>

  </div>
</div>

app/views/pages/dashboard_contractor.html.erb
    <div class="container text-center">
      <div class="grid">

        <div class="frame profile">
          <div class="card-content">
            <%= cl_image_tag current_user.avatar, class: "avatar" %>
            <h2><%= current_user.first_name %> <%= current_user.last_name%></h2>
          </div>
        </div>
        <div class="frame contributions">
          <div class="card-content">

           <h3> <%= @bookings_count %> </h3>
           <p>Bookings received</p>
         </div>
       </div>
       <div class="frame followers">
        <div class="card-content">
          <h3><%= @cashed_in%> $</h3>
          <p>Cashed-in</p>
        </div>
      </div>
      <div class="frame repo">
        <div class="card-content">
          <h3>****</h3>
          <p>Rating</p>
        </div>
      </div>
      <div class="frame bio">
        <div class="card-services">
          <h3>Services provided</h3>
          <% @current_user.contractor.services.each do |serv| %>
          <ul>
            <li> <%= link_to serv.name, service_path(serv) %> </li>
          </ul>
          <% end %>
        </div>
      </div>
      <div class="frame bookings  ">
      <div class="row">
        <div class="col-xs-3 col-md-2">
          <h3>Confirmed Bookings</h3>
          </div>
        <div class="col-xs-12 col-md-10">
         <div class="bookings-in">
          <div class="row">
    <% @bookings_list.each do |bkg| %>
      <ul class="inbox">

        <li class="message">
          <img src="images/gab.png" alt="" class="avatar-large">
          <div class="message-name">
            <h3><%= cl_image_tag bkg.client.user.avatar %></h3>
            <p> <%= bkg.client.user.first_name %></p>
          </div>
          <div class="message-body">
            <p><strong><%= bkg.service.name%></strong></p>
            <p>
             <%= bkg.service.description%>
            </p>
          </div>
          <div class="message-status">
            <p class=""><%= bkg.date %></p>
            <p class="price"><%= bkg.price %> $</p>
          </div>
        </li>

      </ul>
<% end %>
</div>
</div>
</div>
</div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for([ service, booking, review ]) do |form| %>
  <%= form.input :rating %>
  <%= form.input :description, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/services/_card.html.erb
<%= link_to service_path(service) do %>
  <div class="card stretchRight"   style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
  url('<%=  cl_image_path service.photo, height: 300, width: 400, crop: :fill %>')">
  <div class="card-category"><%= service.category %></div>
  <div class="card-description">
    <h2><%= service.name %></h2>
    <p><%= service.location %></p>
  </div>
  <img class="card-user" src="<%= cl_image_path service.contractor.user.avatar, height: 200, width: 200, crop: :fill, :gravity=>"face" %>">
  </div>
<% end %>

app/views/services/_form.html.erb
<%= simple_form_for(@newservice) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%=f.input :name %>
  <%=f.input :description %>
  <%=f.input :price %>
  <%=f.input :location %>
  <%=f.input :category %>
  <%=f.input :photo%>
  <%= f.input :photo_cache, as: :hidden %>

</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/destroy.html.erb
<h1>Services#destroy</h1>
<p>Find me in app/views/services/destroy.html.erb</p>

app/views/services/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/services/index.html.erb
<!-- searchbar -->

<div class="banner pullDown" id="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.2) 50%), url('https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/tHF1OBF/4k-organized-criminal-gangsters-in-dark-parking-lot-doing-a-drug-deal_h7fugeodye_thumbnail-full01.png');">
  <div class="banner-content">
    <h1>Book a service</h1>
    <p>Find the right man for the job</p>





    <%= form_tag services_path, method: :get, remote: true do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
        placeholder: "Find a Service"
        %>
    <% end %>
    </div>

  </div>

<!-- <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/tHF1OBF/4k-organized-criminal-gangsters-in-dark-parking-lot-doing-a-drug-deal_h7fugeodye_thumbnail-full01.png');">
  <div class="banner-content">
    <h1>Book a service</h1>
    <p>Find the right man for the job</p>
    <h4 class="text-center"><input type="text" placeholder="Search a job"> </h4>
  </div>
</div> -->


  <!-- cardlist -->


  <div class="container">
    <div class="row" id="services-cards">
      <% @services.each do |service| %>
      <div class="col-xs-12 col-sm-4" >

          <%= render 'card', service: service %>

    </div>
    <% end %>
  </div>
</div>

app/views/services/index.js.erb
document.getElementById('banner').style.height = '30vh';
// document.getElementById('banner').classList.add('pullUp');
// document.getElementById('banner').classList.remove('pullUp');


function updateServices(page){
const servicesnode = document.getElementById('services-cards');
  servicesnode.insertAdjacentHTML('beforeend', page);
}


document.getElementById('services-cards').innerHTML = "";
<% @services.each do |service|  %>
  updateServices('<%= j render "services/card", service: service %>');
<% end %>

app/views/services/new.html.erb
<h1>Services#new</h1>
<p>Find me in app/views/services/new.html.erb</p>

<%= simple_form_for(@service) do |f| %>
<%=f.input :name %>
<%=f.input :description %>
<%=f.input :price %>
<%=f.input :location %>
<%=f.input :category %>
<%=f.simple_fields_for :pictures, multipart: true do |ff|  %>
  <%= ff.input :url, as: :file %>
  <%= ff.input :url_cache, as: :hidden %>
<% end %>

<%=f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to services', services_path %>

app/views/services/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div id="togglecardsize">
        <div class="service-details">
          <div class="service-links service-element">
            <% if @service.contractor.user == current_user %>
            <%= link_to 'Delete',  @service,  method: :delete, data: { confirm: 'Are you sure?' }%> |
            <%= link_to "Edit", "#", "data-toggle" => "modal", 'data-target' => '#editReviewModal' %> |
            <% end %>
            <%= link_to 'Back', services_path %>
          </div>
          <div class="service-name service-element">
            <h2><%= @service.name %></h2>
          </div>
          <div class="service-description service-element" id="service-description">
            <p><%= @service.description %></p>
          </div>
          <%= cl_image_tag(@service.photo,
          width: 300, height: 240, crop: :fill, class: 'service-image') %>

          <div class="service-element" id="service-move">
            <div class="service-price">
              <p>€ <%= @service.price %></p>
            </div>

            <div class="service-book">
              <%= simple_form_for [@service,  @booking], html: { class: 'form-inline' } do |f|%>
              <%= f.input :date, label: false, required: false, class: " " %>
              <%= f.submit "book", class: "btn btn-primary" %>
              <% end %>
            </div>

            <div class="service-location">
              <%= link_to @service.location, "#", "class" => "btn btn-primary", "onclick" => "ToggleMap()" %>
            </div>
          </div>

        </div>
      </div>
      <div id="map-container"  data-markers="<%= @markers.to_json %>">

      </div>
    </div>
    <!-- list of all the reviews for this service -->
    <div class="reviews-list">
      <h2>Reviews of this service (<%= @service.reviews.count %>)</h2>
      <% @service.reviews.each do |review| %>
      <div class="review">
        <img class="review-user" src="https://www.grabagardener.com/wp-content/themes/storefront-child/assets/img/gardener-profile-6.jpg">
        <div class="review-name">
          <h3><%= review.booking.client.user.first_name %> <%= review.booking.client.user.last_name %></h3>
          <p><%= review.booking.date %></p>
        </div>
        <div class="review-body">
          <p>
            <%= review.description %>
          </p>
        </div>
        <div class="review-status">
          <p class="status pending">Rating  </p>
          <p class="rating">
            <% review.rating.times do %>
            <i class="fas fa-star"></i>
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="editReviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@service) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%=f.input :name %>
          <%=f.input :description %>
          <%=f.input :price %>
          <%=f.input :location %>
          <%=f.input :category %>
          <%=f.input :photo%>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  function createMap() {
    const mapElement = document.getElementById('map');
    const markers = JSON.parse(document.getElementById('map-container').dataset.markers);

    if (mapElement) { // don't try to build a map if there's no div#map to inject in
      // var uluru = ;
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 4,
      center: markers[0]
    });
    var marker = new google.maps.Marker({
      position: markers[0],
      map: map
    });
  }
}
function ToggleMap() {
  var y = document.getElementById("togglecardsize");
  var z = document.getElementById("service-move");
  var p = document.getElementById("service-description")
  var x = document.getElementById("service-map");
  y.classList.add("col-md-8");
  z.style.gridColumn = "1 / span 4";
  z.style.gridRow = "5 / span 1";
  p.style.gridRow = "3 /span 2"
  if (x == null) {
   var map =  `   <div id="service-map" class="stretchRight col-md-4">
   <div class="">
   <div
   id="map"
   style="width: 100%;
   height: 50vh;"
   data-markers="<%#= @markers.to_json %>"
   ></div>
   </div>
   </div>  `
   document.getElementById('map-container').innerHTML = map;
   createMap();
 } else {
  if (x.style.display === "none" ) {
    x.style.display = "block";
    y.classList.add("col-md-8");
    z.style.gridColumn = "1 / span 4";
    z.style.gridRow = "5 / span 1";
    p.style.gridRow = "3 /span 2"
  } else {
    x.style.display = "none";
    y.classList.remove("col-md-8");
    z.style.gridColumn = "2 /span 3";
    z.style.gridRow = "4 / span 1";
    p.style.gridRow = "3 /span 1"
  }
}
}
$(function() {
  $('#booking_date').daterangepicker({
    singleDatePicker: true,
    showDropdowns: true
  },
  function(start, end, label) {

  });
});
</script>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="/about"><i class="about"></i>About us</a>

<%=  %>
  </div>
  <div class="footer-copyright">
    Coded by Ruben, Daniel and Georges
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo-airbnb_clone.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <%= link_to "New Service", "#", "data-toggle" => "modal", 'data-target' => '#NewReviewModal', class: "navbar-wagon-item navbar-wagon-link" %>


    <%= link_to "Browse", services_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Dashboard", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
       <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to dashboard_contractor_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% else %>
  <!-- Login link (when logged out) -->
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <% end %>
</div>

<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>

<!-- modal for a new service -->
<div class="modal fade" id="NewReviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Service</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'services/form' %>
      </div>
    </div>
  </div>
</div>